### ISSUE TITLE
add steamdb commando

### ISSUE THREAD

**Issue by ahamudo** [bakapear/Jibril#1]
**_CONTRIBUTIONU_**

this could work.
an example:
ahamudo: .steamdb ahmadpls
then jibril would reply with: https://i.imgur.com/WC4Utfl.png
but like not in in image cause that's impossible so just make it display info like .steam or .osu
![doremyboi](https://user-images.githubusercontent.com/24731999/37105586-3921e8d2-2238-11e8-83e9-aaeab22bb6c4.png)

**Comment by bakapear** [comment]
well since steamdb does not have a public API for it, I cant include it... Imma try to improve the steam cmd with more information though!
