### ISSUE TITLE
archaic translator command

### ISSUE THREAD

**Issue by ahamudo** [bakapear/Jibril#3]
ahamudo: .archaic fuck this shit, doremy isn't a trap
jiborilo: alas this the horror, d'remy isn't a trapeth

actual translator: https://lingojam.com/EnglishtoShakespearean

_**intuition at it's finest**_
https://pm1.narvii.com/6701/1455622007ad2cf2589544e69570e90789ea580a_hq.jpg

**Comment by bakapear** [comment]
if you give me a translator api with limitless requests sure.
